pipeline:
  clone:
    image: plugins/git
    tags: true

  test:
    image: python:3-alpine
    commands:
      - python setup.py test

  build:
    image: python:3-alpine
      - python setup.py bdist_wheel
      - python setup.py sdist
      - python setup.py sdist --formats=zip

  staging:
    image: shocki/drone-devpi
    server: ${devpi_server}
    index: dietzi/staging
    username: ${devpi_username}
    password: ${devpi_password}
    when:
      branch: master

  release:
    image: shocki/drone-devpi
    server: ${devpi_server}
    index: dietzi/stable
    username: ${devpi_username}
    password: ${devpi_password}
    when:
      event: tag
      status: success