kind: pipeline
name: python-package

steps:
  - name: test
    image: python:3-alpine
    commands:
      - apk update && apk add --no-cache git
      - pip install --upgrade pip setuptools wheel
      - python setup.py test
  - name: build
    image: python:3-alpine
    commands:
      - apk update && apk add --no-cache git
      - pip install --upgrade pip setuptools wheel
      - python setup.py bdist_wheel
      - python setup.py sdist --formats=zip

  - name: publish
    image: shocki/alpine-devpi-client
    commands:
      - devpi use http://devpi.dietzi.mywire.org
      - devpi login dietzi
      - devpi upload dist/*.whl
      - devpi upload dist/*.zip